version: "3.7"

networks:
  frontend:
    ipam:
      config:
        - subnet: 172.21.0.0/24


services:

  mysql:
    image: docker.io/mysql:5.7.32
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - /home/ubuntu/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "w0Rrjyn4"
      MYSQL_DATABASE: "sonarqube"
      MYSQL_USER: "sonarqube"
      MYSQL_PASSWORD: "P1b7JBvP8II4"
    networks:
        frontend:
            ipv4_address: 172.21.0.2


  modern-ecommerce:
    depends_on:
      - mysql
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
        frontend:
            ipv4_address: 172.21.0.3
            

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    restart: unless-stopped
    ports:
      - 8083:8080
      - 50003:50000
    container_name: jenkins
    volumes:
      - /home/ubuntu/data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
        frontend:
            ipv4_address: 172.21.0.4

